"""top_artists

Revision ID: 4d50b126ec47
Revises: 
Create Date: 2019-12-09 15:46:41.491650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d50b126ec47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_artists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('time_range', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('popularity', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'time_range'),
    sa.UniqueConstraint('id', 'time_range')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_artists')
    # ### end Alembic commands ###
